server:
 port: 8888
open:
 ds:
  name: opends
  active: true
  url: jdbc:mysql://127.0.0.1:3306/hbeunews?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
  username: root
  password: Develop_account
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
spring:
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/hbeunews?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
  username: root
  password: Develop_account
 driver-class-name: com.mysql.jdbc.Driver
